# Generated by Django 5.0.3 on 2024-04-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameBoard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("year_published", models.IntegerField()),
                ("rank", models.IntegerField()),
                ("bayes_average", models.FloatField()),
                ("average", models.FloatField()),
                ("users_rated", models.IntegerField()),
                (
                    "abstracts_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("cgs_rank", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "childrens_games_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "family_games_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "party_games_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "strategy_games_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "thematic_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "war_games_rank",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
        ),
    ]
