# Generated by Django 3.2.25 on 2024-04-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GBGAnalysisApp', '0004_auto_20240411_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='gameboard',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gameboard',
            name='mechanics',
            field=models.ManyToManyField(to='GBGAnalysisApp.Mechanics'),
        ),
    ]
